### ISSUE TITLE
Teacher Password - duplicates

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#208]
Hey Andrew, 

Some teachers have two passwords associated with their email addresses because they teach in two different schools. Previously, on the old system, either password worked and would direct them to their class list page with all students. But now only 1 of the passwords is working for them.

**Comment by rennera** [comment]
Hey there, even on the old system, only one of the passwords would work because I can only associate one password to an account. The password on this system will be the first one created when it tries to create the second account it will realize one already exists. On Feb 10, 2023, at 8:54 AM, rasope ***@***.***> wrote:﻿
Hey Andrew,
Some teachers have two passwords associated with their email addresses because they teach in two different schools. Previously, on the old system, either password worked and would direct them to their class list page with all students. But now only 1 of the passwords is working for them.
