### ISSUE TITLE
Issue with Teacher login & teacher move

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#234]
Hey Andrew. I'm running into issues with the update made yesterday.

jtirimac@hwdsb.on.ca (JESSICA TIRIMACO) should have 1 student in site 330, and 14 students in site 830. But the update from yesterday moved all 14 students into site 330.
![image](https://user-images.githubusercontent.com/24963245/229803850-fee583cf-8da1-4069-90b8-72823281ea61.png)

It looks like all those duplicate teachers now have all of their students moved into site 330. Site 330 should only have 92 students in total, but now it has 307. We need to get these students back into their original site.

**Comment by rennera** [comment]
This needs a much larger discussion as it changes the entire data model.  Currently teachers are part of the EDIID and are part of a single school.

What we need to do is allow the teacher to be part of many schools.  The underlying structure will support it but the relationships and model will need to be adapted to support this.

**Comment by rennera** [comment]
you can reset the passwords on the teacher as well

**Comment by rennera** [comment]
is it just the duplicates?

**Comment by rennera** [comment]
the other option would be to use a second email... would solve all the issues.

**Comment by rasope** [comment]
Well they’re technically not duplicates anymore. I deleted all accounts that have duplicate logins 


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Apr 5, 2023, at 6:23 PM, rennera ***@***.***> wrote:




﻿

is it just the duplicates?
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by rasope** [comment]
Well that’s what I’m going to have to do moving forward. The login and passwords for these research projects have already been sent out. I deleted all of these classes for the teachers in their Ontario sites. And I’ll have to manually update their class lists
 for Ontario with new logins and re upload. But do you know why the passwords aren’t working for these site 330 accounts now?


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Apr 5, 2023, at 6:24 PM, rennera ***@***.***> wrote:




﻿

the other option would be to use a second email... would solve all the issues.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by rasope** [comment]
If I know moving forward that I can’t have duplicate emails on the system, then every time I upload a new site for Ontario I’m going to cross reference every email address that’s uploaded under sites 330 and 350 for our research projects to make sure that I’m
 not uploading any duplicate Logins. 


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Apr 5, 2023, at 6:36 PM, Raso, Patricia ***@***.***> wrote:




﻿ Well that’s what I’m going to have to do moving forward. The login and passwords for these research projects have already been sent out. I deleted all of these classes for the teachers in their Ontario sites. And I’ll have to manually update
 their class lists for Ontario with new logins and re upload. But do you know why the passwords aren’t working for these site 330 accounts now?


--
Patricia Raso | Early Development Instrument (EDI) Coordinator
Offord Centre for Child Studies | McMaster University 
(905) 525-9140 ext. ***@***.***
edi.offordcentre.com




On Apr 5, 2023, at 6:24 PM, rennera ***@***.***> wrote:




﻿

the other option would be to use a second email... would solve all the issues.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by rennera** [comment]
We can make adjustments to system to accommodate for sure but it wasn’t designed to have teachers at different schools or in different data sets.Now we could separate on analysis as the ediid is indicative of the other site…On Apr 5, 2023, at 6:40 PM, rasope ***@***.***> wrote:﻿










If I know moving forward that I can’t have duplicate emails on the system, then every time I upload a new site for Ontario I’m going to cross reference every email address that’s uploaded under sites 330 and 350 for our research projects to make sure that I’m

 not uploading any duplicate Logins. 





--

Patricia Raso | Early Development Instrument (EDI) Coordinator

Offord Centre for Child Studies | McMaster University 

(905) 525-9140 ext. ***@***.***

edi.offordcentre.com









On Apr 5, 2023, at 6:36 PM, Raso, Patricia ***@***.***> wrote:









﻿ Well that’s what I’m going to have to do moving forward. The login and passwords for these research projects have already been sent out. I deleted all of these classes for the teachers in their Ontario sites. And I’ll have to manually update

 their class lists for Ontario with new logins and re upload. But do you know why the passwords aren’t working for these site 330 accounts now?





--

Patricia Raso | Early Development Instrument (EDI) Coordinator

Offord Centre for Child Studies | McMaster University 

(905) 525-9140 ext. ***@***.***

edi.offordcentre.com









On Apr 5, 2023, at 6:24 PM, rennera ***@***.***> wrote:









﻿



the other option would be to use a second email... would solve all the issues.

—

Reply to this email directly, 

view it on GitHub, or 

unsubscribe.

You are receiving this because you authored the thread.Message

 ID: ***@***.***>

**Comment by rennera** [comment]
Hey there - is this still an issue?  If so can you let me know a few teachers to test with?

Thanks!

**Comment by rasope** [comment]
Nope. We can close this! We know not to upload duplicate emails and are using the duplicate teacher report to troubleshoot any errors. All good here.
