### ISSUE TITLE
Navigation by "Teacher" speed

### ISSUE THREAD

**Issue by rasope** [RADB/Offord-EDI-2020#239]
When I select "Teacher" from the menu, it lags for about 30 seconds before the teacher page loads. I get stuck/frozen while this page is loading if I try to navigate somewhere else. I avoid using this function because it's so slow, but I would like to use it if it loaded as fast as Site, or Class List.

Can we speed it up? "School" is a bit quicker, but not as quick as Site or Class List- so those are the only ones I end up using. 

![image](https://github.com/RADB/Offord-EDI-2020/assets/24963245/0fc3366e-f2dd-4593-bba0-43d6d8691c93)

**Comment by rennera** [comment]
This will be fixed in the release this week!  Already done in dev.On May 17, 2023, at 10:05 AM, rasope ***@***.***> wrote:﻿
When I select "Teacher" from the menu, it lags for about 30 seconds before the teacher page loads. I get stuck/frozen while this page is loading if I try to navigate somewhere else. I avoid using this function because it's so slow, but I would like to use it if it loaded as fast as Site, or Class List.
Can we speed it up? "School" is a bit quicker, but not as quick as Site or Class List- so those are the only ones I end up using.
